spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  freemarker:
    checkTemplateLocation: false
  datasource:
    url: jdbc:mysql://localhost:3306/personblog?characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
  data:
    redis:
      host: 192.168.88.128
      port: 6379
      password: 2002426
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 100ms

server:
  port: 8077